---
title: "main"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

To set-up Python with RStudio, follow instructions at https://support.rstudio.com/hc/en-us/articles/360023654474-Installing-and-Configuring-Python-with-RStudio.

```{r}
library(pacman)
p_load(tidyverse, here, janitor, lubridate, data.table)
```

# Read data

* Download playoff results with `download_data.py`.
* Download 538 data from https://github.com/fivethirtyeight/checking-our-work-data.

```{r}
nba_538 = read_csv(here("./data/nba_playoffs.csv")) %>% clean_names()
nba_playoff_games = read_csv(here("./data/playoff_games.csv")) %>% clean_names()
team_abbreviations = readLines(here("./data/team_abbreviations.txt"))
```

# Clean data

Schematic of the data frame you need to create:
year | (round) | matchup | team_1 | team_2 | outcome | team_1_seed | team_2_seed | 538_pred

```{r}
# Clean up data
## Each game is represented twice as 2 rows, only need to select one
games_clean = nba_playoff_games %>% 
  select(game_id, game_date, matchup, team_abbreviation, wl) %>%
  distinct(game_id, .keep_all = T)

## Create matchup variable in alphabetical order (A-B), outcome variable, and year variable
games_clean = games_clean %>%
  separate(matchup, sep = "( @ )|( vs. )", into = c("team_1", "team_2")) %>%
  mutate(matchup = paste(pmin(team_1, team_2), pmax(team_1, team_2), sep = "-"),
         outcome = ifelse(team_abbreviation == team_1 & wl == "W", team_1, team_2),
         year = year(game_date))

## Get series end date (playoff_outcome_date) and series begin date (forecast_date)
## and only keep last game with the series outcome
games_clean = games_clean %>%
  select(year, game_date, matchup, team_1, team_2, outcome) %>%
  group_by(year, matchup) %>%
  mutate(playoff_outcome_date = max(game_date),
         forecast_date = min(game_date) - 1) %>%
  arrange(desc(game_date)) %>% 
  slice(1) %>%
  ungroup()

## Select necessary rows
games_clean = games_clean %>%
  select(year, playoff_outcome_date, forecast_date, matchup, team_1, team_2, outcome) %>%
  arrange(desc(playoff_outcome_date))
```

```{r}
# Clean up team names dict
team_abb_tb = tibble(team_abbreviations) %>%
  separate(team_abbreviations, sep = "\t- ", into = c("abb", "full_team_name")) %>%
  mutate(team_name = word(full_team_name, -1)) %>%
  mutate(team_name = ifelse(team_name == "Blazers", "Trail Blazers", team_name))
```

```{r}
# Clean up 538 data
## Select columns
nba_538_clean = nba_538 %>%
  select(forecast_date, team, starts_with("make"), 
         starts_with("win"), ends_with("outcome"))

## Get seed
nba_538_clean = nba_538_clean %>%
  pivot_longer(cols = starts_with("seed"), names_to = "seed", values_to = "indicator") %>%
  filter(indicator == 1) %>%
  mutate(seed = as.numeric(gsub(".*_(.+)_.*", "\\1", seed)))

## Get last round made by team
nba_538_clean = nba_538_clean %>%
  mutate(round = case_when(make_finals_outcome == 1 ~ 4,
                           make_conf_finals_outcome == 1 ~ 3,
                           make_conf_semis_outcome == 1 ~ 2,
                           make_playoffs_outcome == 1 ~ 1)) %>%
  select(forecast_date, team, seed, round, starts_with("make"), starts_with("win"))

## Join to team abbreviation
nba_538_clean = nba_538_clean %>%
  inner_join(., team_abb_tb, by = c("team" = "team_name"))
```

```{r}
# Join tables together
## Rolling join with data.table 
games_clean_dt = as.data.table(games_clean)
games_clean_dt[, rolling_date := forecast_date]
nba_538_clean_dt = as.data.table(nba_538_clean)

setkey(games_clean_dt, team_1, rolling_date)
setkey(nba_538_clean_dt, abb, forecast_date)

## Join to first team
tmp1 = nba_538_clean_dt %>% rename_with(~ paste0(.x, "_1"))
tmp1 = tmp1[games_clean_dt, roll = TRUE]
tmp1[, rolling_date := forecast_date]
setkey(tmp1, team_2, rolling_date)

## Join to second team
tmp2 = nba_538_clean_dt %>% rename_with(~ paste0(.x, "_2"))
games_pred_dt = tmp2[tmp1, roll = TRUE]
```

```{r}
# Clean up joined table
## Filter out non-NBA matchups
games_pred = as_tibble(games_pred_dt)
games_pred = games_pred %>%
  arrange(desc(playoff_outcome_date)) %>%
  drop_na()

## Get prediction for the correct round
games_pred = games_pred %>% 
  mutate(round = pmin(round_1, round_2),
         pred_538_1 = case_when(round == 4 ~ win_finals_1,
                                round == 3 ~ make_finals_1,
                                round == 2 ~ make_conf_finals_1,
                                round == 1 ~ make_conf_semis_1),
         pred_538_2 = case_when(round == 4 ~ win_finals_2,
                                round == 3 ~ make_finals_2,
                                round == 2 ~ make_conf_finals_2,
                                round == 1 ~ make_conf_semis_2))

## Select columns
games_pred = games_pred %>%
  select(year, playoff_outcome_date, round, matchup,
         team_1, abb_1, team_2, abb_2, seed_1, seed_2, 
         pred_538_1, pred_538_2, outcome)

## Generate predictions by 538 and seed
games_pred = games_pred %>%
  mutate(pred_seed = ifelse(seed_1 < seed_2, abb_1,
                            ifelse(seed_2 < seed_1, abb_2, NA)),
         pred_538 = ifelse(pred_538_1 > pred_538_2, abb_1,
                            ifelse(pred_538_2 > pred_538_1, abb_2, NA))) %>%
  mutate(pred_seed = ifelse(year == 2016 & matchup == "CLE-GSW", 
                            "GSW", pred_seed)) # Use W-L record for the 2016 finals (both were 1st seed)
```

```{r}
# Check data is correct
summary(games_pred$pred_538_1 + games_pred$pred_538_2) # sum of predictions = 1
```

```{r}
write_csv(games_pred, file = here("./data/games_pred.csv"))
```

## Plots

```{r}
# Plot prediction % by year
games_pred %>%
  group_by(year) %>%
  summarize(pred_seed = sum(pred_seed == outcome),
            pred_538 = sum(pred_538 == outcome)) %>%
  pivot_longer(-year, names_to = "prediction", values_to = "n_games_correct") %>%
  ggplot(aes(x = year, y = n_games_correct, color = prediction)) + 
  geom_point() +
  geom_line() + 
  ylim(c(0, 15)) +
  theme_bw()
```

```{r}
# Are the wrong predictions by 538 marginal?
games_pred %>%
  mutate(correct_prediction = (pred_538 == outcome),
         pred_538_prob = ifelse(pred_538_1 > pred_538_2, pred_538_1,
                            ifelse(pred_538_2 > pred_538_1, pred_538_2, 0.5))) %>%
  ggplot(aes(x = pred_538_prob)) + 
  geom_density(aes(fill = correct_prediction), alpha = 0.5) + 
  geom_histogram(aes(fill = correct_prediction), alpha = 0.5) + 
  xlim(c(0.5, 1.0)) +
  theme_bw()

# Are the wrong predictions by seeding marginal?
games_pred %>%
  mutate(correct_prediction = (pred_seed == outcome),
         pred_seed_diff = abs(seed_1 - seed_2)) %>%
  ggplot(aes(x = pred_seed_diff)) + 
  # geom_density(aes(fill = correct_prediction), alpha = 0.5) + 
  geom_histogram(aes(fill = correct_prediction), position = "dodge", alpha = 0.5) +
  # xlim(c(0.5, 1.0)) +
  theme_bw()
```

```{r}
# Is the prediction power mainly due to the round or the seeding difference?
logit_df = games_pred %>%
  mutate(y_538 = (pred_538 == outcome),
         y_seed = (pred_seed == outcome),
         seed_diff = abs(seed_1 - seed_2),
         round = round)

glm(y_538 ~ round + seed_diff, data = logit_df, family = "binomial") %>%
  summary()

glm(y_seed ~ round + seed_diff, data = logit_df, family = "binomial") %>%
  summary()
```
